[tools]
rojo = "rojo-rbx/rojo@7.4.4"
darklua = "seaofvoices/darklua@0.15.0"
lune = "lune-org/lune@0.8.9"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.4.1"
