name: Pushed

on:
  push:
    paths:
      - '**.luau'
      - '**.lua'
      - '**.rbxm'
      - '**.json'
      - '**.yml'
  pull_request:
    paths:
      - '**.luau'
      - '**.lua'
      - '**.rbxm'
      - '**.json'
      - '**.yml'

permissions:
  contents: write

jobs:
  build-script:
    name: Bundle and Upload Fluent Renewed
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install Necessary Tools
        run: |
          rokit trust rojo-rbx/rojo
          rokit trust lune-org/lune
          rokit trust seaofvoices/darklua
          rokit trust UpliftGames/wally
          rokit trust JohnnyMorganz/wally-package-types
          rokit install

      - name: Build
        run: lune run Build bundle header=Lune/Build/Header.luau minify=true ci-mode=true

      - name: Upload Minified Fluent Renewed to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent.luau
          path: Distribution/Fluent.luau

      - name: Upload Fluent Renewed Model to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent.rbxm
          path: Distribution/Fluent.rbxm